apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: hebomah
  labels:
    app: db
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 20
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: db-secret
        name: db-deployment
        image: harbor.dev.afsmtddso.com/henryebomah/db@sha256:bf8b781180340b62b8cfec48ca7548c2f61f4287e8ea505b9abd3ccf4d3d721e
        ports:
        - containerPort: 5432
